apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-app-config
  namespace: finance-app
data:
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  EUREKA_INSTANCE_HOSTNAME: "localhost"
