apiVersion: v1
kind: Secret
metadata:
  name: finance-app-secrets
  namespace: finance-app
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "manager"
  APP_JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
  MYSQL_ROOT_PASSWORD: "manager"
